config/routes.rb
Rails.application.routes.draw do
  root 'static#index'
  resources :mums do
    resources :cousins
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cousin.rb
class Cousin < ApplicationRecord
  belongs_to :mum
end

app/models/mum.rb
class Mum < ApplicationRecord
  has_many :cousins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cousins_controller.rb
class CousinsController < ApplicationController
  before_action :set_cousin, only: [:show, :edit, :update, :destroy]

  # GET /cousins
  # GET /cousins.json
  def index
    @cousins = Cousin.all
  end

  # GET /cousins/1
  # GET /cousins/1.json
  def show
    @mum = Mum.find(params[:mum_id])
  end

  # GET /cousins/new
  def new
    @cousin = Cousin.new
    @mum = Mum.find(params[:mum_id])
  end

  # GET /cousins/1/edit
  def edit
    @mum = Mum.find(params[:mum_id])
  end

  # POST /cousins
  # POST /cousins.json
  def create
    @cousin = Cousin.new(cousin_params)
    @mum = Mum.find(params[:mum_id])
    @cousin.mum = @mum

    respond_to do |format|
      if @cousin.save
        format.html { redirect_to mum_path(@cousin), notice: 'Gen2 was successfully created.' }
        format.json { render :show, status: :created, location: @cousin }
      else
        format.html { render :new }
        format.json { render json: @cousin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cousins/1
  # PATCH/PUT /cousins/1.json
  def update
    @mum = Mum.find(params[:mum_id])
    respond_to do |format|
      if @cousin.update(cousin_params)
        format.html { redirect_to mum_path(@mum), notice: 'Gen2 was successfully updated.' }
        format.json { render :show, status: :ok, location: @cousin }
      else
        format.html { render :edit }
        format.json { render json: @cousin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cousins/1
  # DELETE /cousins/1.json
  def destroy
    @mum = Mum.find(params[:mum_id])
    @cousin.destroy
    respond_to do |format|
      format.html { redirect_to mum_path(@mum), notice: 'Cousin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cousin
      @cousin = Cousin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cousin_params
      params.require(:cousin).permit(:name, :gender, :married, :mum_id)
    end
end

app/controllers/mums_controller.rb
class MumsController < ApplicationController
  before_action :set_mum, only: [:show, :edit, :update, :destroy]

  # GET /mums
  # GET /mums.json
  def index
    @mums = Mum.all
  end

  # GET /mums/1
  # GET /mums/1.json
  def show
    @cousins = Cousin.all
  end

  # GET /mums/new
  def new
    @mum = Mum.new
  end

  # GET /mums/1/edit
  def edit
  end

  # POST /mums
  # POST /mums.json
  def create
    @mum = Mum.new(mum_params)

    respond_to do |format|
      if @mum.save
        format.html { redirect_to @mum, notice: 'Gen1 was successfully created.' }
        format.json { render :show, status: :created, location: @mum }
      else
        format.html { render :new }
        format.json { render json: @mum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mums/1
  # PATCH/PUT /mums/1.json
  def update
    respond_to do |format|
      if @mum.update(mum_params)
        format.html { redirect_to @mum, notice: 'Gen1 was successfully updated.' }
        format.json { render :show, status: :ok, location: @mum }
      else
        format.html { render :edit }
        format.json { render json: @mum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mums/1
  # DELETE /mums/1.json
  def destroy
    @mum.destroy
    respond_to do |format|
      format.html { redirect_to mums_url, notice: 'Gen1 was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mum
      @mum = Mum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mum_params
      params.require(:mum).permit(:name, :relation, :married)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cousins_helper.rb
module CousinsHelper
end

app/helpers/mums_helper.rb
module MumsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/cousins/_form.html.erb
<%= form_with(model: cousin, url: [@mum, @cousin], local: true) do |form| %>
  <% if cousin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cousin.errors.count, "error") %> prohibited this cousin from being saved:</h2>

      <ul>
      <% cousin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :married %>
    <%= form.check_box :married %>
  </div>

  <div class="field">
    <%= collection_select(:cousin, :mum_id, Mum.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cousins/edit.html.erb
<h1>Editing Cousin</h1>

<%= render 'form', cousin: @cousin %>

<%= link_to 'Show', mum_path(@mum) %> |
<%= link_to 'Back', mum_cousins_path(@mum) %>

app/views/cousins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cousins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Married</th>
      <th>Mum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cousins.each do |cousin| %>
      <tr>
        <td><%= cousin.name %></td>
        <td><%= cousin.gender %></td>
        <td><%= cousin.married %></td>
        <td><%= cousin.mum_id %></td>
        <td><%= link_to 'Show', mum_cousin_path %></td>
        <td><%= link_to 'Edit', edit_mum_cousin_path(@mum,cousin) %></td>
        <td><%= link_to 'Destroy', mum_cousin_path(@mum,cousin), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cousin', new_mum_cousin_path %>

app/views/cousins/new.html.erb
<h1>New Cousin</h1>

<%= render 'form', cousin: @cousin %>

<%= link_to 'Back', mum_cousins_path %>

app/views/cousins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cousin.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @cousin.gender %>
</p>

<p>
  <strong>Married:</strong>
  <%= @cousin.married %>
</p>

<p>
  <strong>Mum:</strong>
  <%= @cousin.mum_id %>
</p>

<%= link_to 'Edit', edit_mum_cousin_path(@mum,@cousin) %> |
<%= link_to 'Delete', mum_cousin_path(@mum,@cousin) %> |
<%= link_to 'Back', mum_cousins_path(@mum) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sparta Nested Routes Homework</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/nav' %>
    <%= yield %>
  </body>
</html>

app/views/mums/_form.html.erb
<%= form_with(model: mum, local: true) do |form| %>
  <% if mum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mum.errors.count, "error") %> prohibited this mum from being saved:</h2>

      <ul>
      <% mum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :relation %>
    <%= form.text_field :relation %>
  </div>

  <div class="field">
    <%= form.label :married %>
    <%= form.check_box :married %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mums/edit.html.erb
<h1>Editing Mum</h1>

<%= render 'form', mum: @mum %>

<%= link_to 'Show', @mum %> |
<%= link_to 'Back', mums_path %>

app/views/mums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mums</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Relation</th>
      <th>Married</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mums.each do |mum| %>
      <tr>
        <td><%= mum.name %></td>
        <td><%= mum.relation %></td>
        <td><%= mum.married %></td>
        <td><%= link_to 'Show', mum %></td>
        <td><%= link_to 'Edit', edit_mum_path(mum) %></td>
        <td><%= link_to 'Destroy', mum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mum', new_mum_path %>

app/views/mums/new.html.erb
<h1>New Mum</h1>

<%= render 'form', mum: @mum %>

<%= link_to 'Back', mums_path %>

app/views/mums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mum.name %>
</p>

<p>
  <strong>Relation:</strong>
  <%= @mum.relation %>
</p>

<p>
  <strong>Married:</strong>
  <%= @mum.married %>
</p>

<nav>
  <%= link_to 'New Cousin', new_mum_cousin_path(@mum) %>
  <%= link_to 'Edit', edit_mum_path(@mum) %> |
  <%= link_to 'Back', mums_path %>
</nav>

<table>
  <thead>
    <th>Name</th>
    <th>Gender</th>
    <th>Married</th>
    <th>Mum</th>
    <th colspan="3"></th>
  </thead>
  <tbody>
    <% @cousins.each do |cousin| %>
        <tr>
          <td><%= cousin.name %></td>
          <td><%= cousin.gender %></td>
          <td><%= cousin.married %></td>
          <td><%= link_to 'See more', mum_cousin_path(@mum) %></td>
          <td><%= link_to 'Edit', edit_mum_cousin_path(@mum,cousin) %></td>
          <td><%= link_to 'Delete', mum_cousin_url(@mum,cousin), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_nav.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Generation 1', mums_path %>